### ISSUE TITLE
Retropie Shortcut does not appear on OSMC menu

### ISSUE THREAD

**Issue by mrmwiebe** [mcobit/retrosmc#25]
Did fresh install of OSMC on SD card, then SSH'ed in and installed this script, however I don't see any link to RetroPie in the programs folder even though I installed and re-installed the shortcut from the RetroSMC installer.

**Comment by mcobit** [comment]
Hello,
Would be good if you could post problems in this thread:
https://discourse.osmc.tv/t/howto-retrosmc-retrogaming-on-osmc/6671

Is there any error, when you install the launcher addon?
Maybe it did not download the tgz from github because of some connection issue.

You can try to scroll up when installing via ssh. It should reveal if there is an error.

**Comment by ShaneDrury** [comment]
I _think_ it's because the README is wrong: 

```
wget https://raw.githubusercontent.com/mcobit/retrosmc/direct/install-retrosmc.sh
```

Should be:

```
wget https://raw.githubusercontent.com/mcobit/retrosmc/master/install-retrosmc.sh
```

i.e. `direct -> master`. The `direct` branch is 14 commits behind master and has an old URL for the launcher script.

**Comment by mcobit** [comment]
Correct, fixed.
