### ISSUE TITLE
Cannot add Retrosmc as shortcut

### ISSUE THREAD

**Issue by gsantner** [mcobit/retrosmc#37]
Hi there, I am on latest version of retrosmc/master.
Everytime I want to add retrosmc as a shortcut to menu, Emulationstation starts immediately. So I cannot finish adding it to Kodi menu.

**Comment by NSF12345** [comment]
Hi gsantner
Is this still an issue for you?
If so, let me know which version of osmc you're running, and which skin you're using and I'll see if I can replicate/help

Nick

**Comment by gsantner** [comment]
I'm gonna setup a new SD on my Pi next week and try it again. Can you tell me which version/branch I should take right now? Is _testing_ ready?

**Comment by NSF12345** [comment]
I'm running osmc 2017.04-1 (Linux 4.4.27-9-osmc) with RetroPie 4.2.3, installed a couple of days go using install_retrosmc.sh version 0.008. I also use the Amber skin. I have a spare as card so I can install the versions you're using in order to help, however chances are a fresh install will sort it.

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about
